package Modelo;
// Generated 01-abr-2018 12:49:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;

/**
 * Profesor generated by hbm2java
 */
public class Profesor {


     private String dni;
     private String nombre;
     private String apellidos;
     private Date fechaAlta;
     private String departamento;

    public Profesor() {
    }

    public Profesor(String dni, String nombre, String apellidos, Date fechaAlta, String departamento) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechaAlta = fechaAlta;
       this.departamento = departamento;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Profesor other = (Profesor) obj;
        if (!Objects.equals(this.dni, other.dni)) {
            return false;
        }
        if (!Objects.equals(this.nombre, other.nombre)) {
            return false;
        }
        if (!Objects.equals(this.apellidos, other.apellidos)) {
            return false;
        }
        if (!Objects.equals(this.departamento, other.departamento)) {
            return false;
        }
        if (!Objects.equals(this.fechaAlta, other.fechaAlta)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Profesor{" + "dni=" + dni + ", nombre=" + nombre + ", apellidos=" + apellidos + ", fechaAlta=" + fechaAlta + ", departamento=" + departamento + '}';
    }




}


