package gestionCitas;
// Generated Apr 23, 2018 7:31:25 PM by Hibernate Tools 4.3.1



/**
 * Cita generated by hbm2java
 */
public class Cita  implements java.io.Serializable {


     private String id;
     private String empresa;
     private String urlEmpresa;
     private String horaCita;
     private Double precio;

    public Cita() {
    }

	
    public Cita(String id) {
        this.id = id;
    }
    public Cita(String id, String empresa, String urlEmpresa, String horaCita, Double precio) {
       this.id = id;
       this.empresa = empresa;
       this.urlEmpresa = urlEmpresa;
       this.horaCita = horaCita;
       this.precio = precio;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getUrlEmpresa() {
        return this.urlEmpresa;
    }
    
    public void setUrlEmpresa(String urlEmpresa) {
        this.urlEmpresa = urlEmpresa;
    }
    public String getHoraCita() {
        return this.horaCita;
    }
    
    public void setHoraCita(String horaCita) {
        this.horaCita = horaCita;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


